# Generated by Django 4.2 on 2023-05-09 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0011_session'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='psychologists',
            field=models.ManyToManyField(blank=True, related_name='chats_ps', to='psychologists.psychologist'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chats_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
