# Generated by Django 4.2 on 2023-05-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_psychologists_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
