# Generated by Django 4.1.1 on 2023-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='psychologists/prof_im.png', upload_to='psychologists/profile_images/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
