# Generated by Django 4.1.1 on 2023-04-04 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0001_initial'),
        ('users', '0002_profile_profile_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='comments',
            field=models.ManyToManyField(through='users.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
