# Generated by Django 4.2 on 2023-05-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0003_psychologist_last_login_psychologist_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
