# Generated by Django 4.2 on 2023-05-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0005_remove_psychologist_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
    ]
