# Generated by Django 4.2 on 2023-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0006_remove_profile_bio_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='is_psychologist',
            field=models.BooleanField(default=True),
        ),
    ]
