# Generated by Django 4.2 on 2023-05-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0008_remove_psychologist_is_psychologist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ps',
            new_name='user',
        ),
    ]
