# Generated by Django 4.2 on 2023-05-07 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0009_rename_ps_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentUserPsychologist',
        ),
    ]
