# Generated by Django 4.2 on 2023-05-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0010_rename_comment_commentuserpsychologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('await', 'Await'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.psychologist')),
                ('users', models.ManyToManyField(related_name='session_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
