# Generated by Django 4.1.7 on 2023-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='articles/article.png', upload_to='articles/images/'),
        ),
    ]
