# Generated by Django 4.2 on 2023-05-10 06:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0014_alter_session_status'),
        ('articles', '0007_commentarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychologists.psychologist'),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
