# Generated by Django 4.2 on 2023-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='users_profile_images/prof_im.png', upload_to='users_profile_images/'),
        ),
    ]
