# Generated by Django 4.2 on 2023-05-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0005_remove_psychologist_average_rating_and_more'),
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
