# Generated by Django 4.2 on 2023-05-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inf',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
